# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Summer 2018 Eth Magicians Meeting
tagline:          'Fellowship of Ethereum Magicians Summer Meeting in Berlin 2018'
description:      '<a href="http://ethereum-magicians.org">Fellowship of Ethereum Magicians</a> gathering in Berlin for technical discussions, July 2018'
url:              https://ethereum-magicians.github.io/
baseurl:          /berlin-council
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:
  url:
  
permalink: /:title/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
# version:            3.6.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/ethereum-magicians/berlin-council/
